site_name: Bipes4RP2040

nav:
  - Home: index.md
  - Introduction: intro.md
  - Program: program.md
  - Parts: parts.md
  - Breadboard: breadboard.md
  - Raspberry Pi Pico: pico.md
  - Installing MicroPython: install.md
  - Introducing BIPES: bipes.md
  - Labs:
    - Blink Onboard LED: labs/onboardBlink.md
    - Alternating LEDs: labs/alternatingBlink.md
    - Button Press (Polling): labs/buttonPressPoll.md
    - Button Press (Interrupt): labs/buttonPressInterrupt.md
    - Pulse Width Modulation: labs/pwm.md
    - Analog to Digital Converter: labs/adc.md
    - Photo Resistor: labs/photoResistor.md
    - NeoPixel Display: labs/neopixel.md
    - Digital Display: labs/ssd1306.md
    - Joystick: labs/joystick.md
    - Buzzer: labs/buzzer.md

copyright: # should remain a link to the original theme
   <div>
     <a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png" /></a><br />This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/">Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License</a>.
   </div>

theme:
  name: material
  features:
    - navigation.footer

site_description: 'Resources for teaching computational concepts using BIPES and the Raspberry Pi Pico.  All content licensed Creative Commons ShareAlike Attribution Noncommercial'
site_author: 'Jim Tannenbaum'
repo_name: 'GitHub Repo'
repo_url: 'https://github.com/jetannenbaum/Bipes4RP2040'

edit_uri: 'blob/master/docs'
plugins:
  - search
markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.highlight:
      linenums: true
  - pymdownx.details
  - pymdownx.superfences


