site_name: Bipes4RP2040

nav:
  - Home: index.md
  - Introduction: intro.md
  - Raspberry Pi Pico: pico.md
  - Installing MicroPython: install.md
  - Introducing BIPES: bipes.md

theme:
  material

site_description: 'Resources for teaching computational concepts using BIPES and the Raspberry Pi Pico.  All content licensed Creative Commons ShareAlike Attribution Noncommercial'
site_author: 'Jim Tannenbaum'
repo_name: 'GitHub Repo'
repo_url: 'https://github.com/jetannenbaum/Bipes4RP2040'

edit_uri: 'blob/master/docs'
plugins:
  - search
markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.highlight:
      linenums: true
  - pymdownx.details
  - pymdownx.superfences


